### ISSUE TITLE
Incorrect credentials uploading a shapefile

### ISSUE THREAD

**Issue by anmaro13** [samapriya/geeup#1]
Hi, 

I'm trying to upload a shapefile using this command: 
`geeup tabup -u email@gmail.com --source SOURCE --dest users/user/folder`

And when it ask me the password, I introduce the refresk token created on the credentials file when you execute the "earthengine authenticate" command , but it gives me the next error:

`ERROR:root:Incorrect credentials. Probably. If you are sure the credentials are OK, refresh the authentication token. If it did not work report a problem. They might have changed something in the Matrix.`

It's another token that I have to use or it has changed something in their Matrix ?. 

Thank you, 
Andrea

**Comment by samapriya** [comment]
Hi @anmaro13 ,
Let us break down your problem in three solutions
* The password you should be using is the Gmail password not the credentials token that you generated. 
* If it still gives you an error a couple of things could be happening including the fact that you have to allow [less secure apps](https://support.google.com/cloudidentity/answer/6260879?hl=en). 
* If that doesn't work I have noticed this behavior before and it seems like an intermittent problem with Google authentication and fixes itself after a couple of hours. For now, since I cannot replicate this issue I would recommend you wait for sometime and try again. If the problem persists reopen the issue, 

Hope this helps
