### ISSUE TITLE
Primary path in each source must not be empty

### ISSUE THREAD

**Issue by matthiasdemuzere** [samapriya/geeup#14]
I am trying to upload one geotif as a test, using the following command:
`geeup upload --source somepath/somefolder --dest users/username/imagecollection -u user@gmail.com -m somepath/metadata.csv`

The metadata consists out of a csv file with two lines:
> id_no
> filename

When running this, I get the following message:

> Password: 
> Collection users/username/imagecollection already exists
> Collection already exists. 1 assets left for upload to users/username/imagecollection
> Processing image 1 out of 1: /somepath/somefolder/myfile.tif
> invalid syntax (<unknown>, line 2)
> Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
> Primary path in each source must not be empty.

To me it is unclear what it is referring to? Any ideas?

**Comment by samapriya** [comment]
Always supply the full path to folder my guess is you are not supplying that because you reported your issue with "some path" instead of pasting your actual command that failed. I cannot say if you are putting the order req correctly. Also, I cannot comment without the metadata file, the id_no has the filename without the .tif extension. Also as a piece of advice put all path within double quotes to avoid any slashes creating an escape

```
geeup upload --source "somepath/somefolder" --dest "users/username/imagecollection" -u "user@gmail.com" -m "somepath/metadata.csv"
```


```
id_no
filename1
filename2
```

**Comment by matthiasdemuzere** [comment]
Of course I have put the full path. I just changed that for this 
example. And yes, the id number has the file name without the extension.
So this is not solved yet, and thus I dont see a reason to close this 
issue?

If there are specific order requirements, it could be good to list 
those? As such I can try again.

**Comment by samapriya** [comment]
Hey @matthiasdemuzere 
I closed this issue because I am unable to reproduce this issue. I have no way to solve something without replicating the problem. Hope that explains it.  Once last thing I would recommend is upgrade to geeup v0.3.1 and trying using the following setup to see if the selenium setup is able to log into your earth engine account. This opens a firefox browser and automatically logs into your earthengine account to establish setup

```
geeup selsetup
```

Best wishes,
Sam
