### ISSUE TITLE
dates

### ISSUE THREAD

**Issue by tschults** [samapriya/geeup#45]
Thank you a lot for this amazing code. 
Could you please add the functionality to add dates to the metadata of the uploaded tiff files?

**Comment by samapriya** [comment]
I am not sure I understand, to add dates you can simply have the system:time_start and system:time_end columns in your CSV and that will add dates to your GeoTiff but this is something the user has to create at their end because they are so data type-specific and is not something that is embedded as a Tiff property

**Comment by tschults** [comment]
You are right. Thank you a lot for your suggestion!
