### ISSUE TITLE
Error: Unable to open tif. (Error code: 3) when uploading 

### ISSUE THREAD

**Issue by fernandobezares** [samapriya/geeup#46]
Dear Samapriya,

I am very interested in your developtments for gee both geeup and geeadd. Thank you for your great contribution!

I have installed geeup in a conda environment (following the instructions in your github). I managed to install it and run the upload command. However, when GEE is ingesting the files I get the following error: 

**Error: Unable to open XXXXXX.tif. (Error code: 3)** 

I have not been able to find information of this type of error. Only this [thread in stack exchange](https://gis.stackexchange.com/questions/382845/error-unable-to-open-image-while-ingesting-into-earth-engine)

Are you familiar with it or do you suspect what could be going on?

I have tried to use a smaller tiff, but I get the same error. 

Thank you

**Comment by samapriya** [comment]
Unfortunately this seems be an error at GEE side I would make sure the cookies you are using is the for the same account that is ingesting the data. Outside that I would not be able to add too more insight into this issue and this has happened to me intermittently in the past

**Comment by fernandobezares** [comment]
Hi, thank you for your quick answer! 
Indeed I have reset the cookies making sure they were from the same google account and it worked! 
Thank you very much for your help.

**Comment by cpgu98** [comment]
Hello! I had the same problem when using geeup to upload rasters to GEE assets.

**Error: Unable to open xxxx.tif. (Error code: 3)**

I found it seems to be a problem with my account. My account is blocked to run batch tasks due to some previous wrong operations. When I used a new account, I successfully completed the upload using the same steps.

Therefore, you can check if the account is blocked for batch tasks.
